package uk.co.lightapps.app.forex.trades.domain;

/**
 * @author Asif Akhtar
 * 26/10/2020 20:51
 */
public enum Pair {
    EURUSD, USDCHF, GOLD, AUDCHF, GBPUSD, EURNZD, USDCAD, GBPJPY, CADCHF, AUDNZD, CADJPY, EURCAD, EURAUD,
    NZDUSD, CHFJPY, AUDUSD, EURJPY, AUDJPY, GBPCAD, AUDCAD, NZDCAD, USDTRY, EURCHF, USDJPY, EURGBP, NZDJPY, SILVER, NZDCHF, OIL
}
