server:
  port: 5002

spring.jackson:
  date-format: yyyy-MM-dd HH:mm:ss

spring:
  data:
    mongodb:
      database: assets-tracker
      username: assets
      password: assets1
  security:
    user:
      name: user
      password: pass
jwt:
  secret: javainuse